# fly.toml app configuration file generated for generator-zadan on 2025-07-30T12:34:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'generator-zadan'
primary_region = 'waw'

[build]

[env]
  FLASK_APP = "main.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
