services:
  - type: web
    name: generator
    env: python
    region: frankfurt
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    branch: main
    autoDeploy: true